# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='\u7528\u6237\u540d\uff0c\u7528\u4e8e\u767b\u9646', max_length=15)),
                ('password', models.CharField(max_length=32)),
                ('telephone', models.CharField(blank=True, help_text='\u9009\u586b\uff0c\u7528\u4e8e\u5907\u6848', max_length=15)),
                ('email', models.EmailField(help_text='\u9009\u586b\uff0c\u7528\u4e8e\u5907\u6848', max_length=15)),
                ('name', models.CharField(help_text='\u8ba4\u8bc1\u5b9e\u540d', max_length=45)),
                ('credit', models.CharField(choices=[(3, 'A'), (2, 'B'), (1, 'C'), (0, 'X')], help_text='\u4fe1\u7528\u989d\u5ea6', max_length=1)),
                ('idcardnumber', models.CharField(help_text='\u8eab\u4efd\u8bc1\u53f7\u5b9a\u957f18\u4f4d', max_length=18, unique=True)),
                ('gender', models.CharField(choices=[(0, '\u7537'), (1, '\u5973')], max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('_createtime', models.DateTimeField(help_text='\u6ce8\u518c\u65f6\u95f4')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
