# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='_createtime',
            field=models.CharField(help_text='\u6ce8\u518c\u65f6\u95f4', max_length=20),
        ),
    ]
