# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161124_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
