# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161124_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('\u7537', '\u7537'), ('\u5973', '\u5973')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='level',
            field=models.CharField(choices=[('\u4e3b\u4efb\u533b\u5e08', '\u4e3b\u4efb\u533b\u5e08'), ('\u526f\u4e3b\u4efb\u533b\u5e08', '\u526f\u4e3b\u4efb\u533b\u5e08'), ('\u4e3b\u6cbb\u533b\u5e08', '\u4e3b\u6cbb\u533b\u5e08'), ('\u4f4f\u9662\u533b\u5e08', '\u4f4f\u9662\u533b\u5e08')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='level',
            field=models.CharField(choices=[('\u4e00\u7ea7\u4e19\u7b49', '\u4e00\u7ea7\u4e19\u7b49'), ('\u4e00\u7ea7\u4e59\u7b49', '\u4e00\u7ea7\u4e59\u7b49'), ('\u4e00\u7ea7\u7532\u7b49', '\u4e00\u7ea7\u7532\u7b49'), ('\u4e8c\u7ea7\u4e19\u7b49', '\u4e8c\u7ea7\u4e19\u7b49'), ('\u4e8c\u7ea7\u4e59\u7b49', '\u4e8c\u7ea7\u4e59\u7b49'), ('\u4e8c\u7ea7\u7532\u7b49', '\u4e8c\u7ea7\u7532\u7b49'), ('\u4e09\u7ea7\u4e19\u7b49', '\u4e09\u7ea7\u4e19\u7b49'), ('\u4e09\u7ea7\u4e59\u7b49', '\u4e09\u7ea7\u4e59\u7b49'), ('\u4e09\u7ea7\u7532\u7b49', '\u4e09\u7ea7\u7532\u7b49'), ('\u4e09\u7ea7\u7279\u7b49', '\u4e09\u7ea7\u7279\u7b49')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(blank=True, choices=[('\u666e\u901a', '\u666e\u901a'), ('\u4e13\u79d1', '\u4e13\u79d1')], help_text='\u533b\u7597\u670d\u52a1\u662f\u5426\u4e13\u79d1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='credit',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('X', 'X')], help_text='\u4fe1\u7528\u989d\u5ea6', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, help_text='\u9009\u586b\uff0c\u7528\u4e8e\u5907\u6848', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('\u7537', '\u7537'), ('\u5973', '\u5973')], max_length=1),
        ),
    ]
