# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id_hospital', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('level', models.CharField(choices=[(0, '\u4e00\u7ea7\u4e19\u7b49'), (1, '\u4e00\u7ea7\u4e59\u7b49'), (2, '\u4e00\u7ea7\u7532\u7b49'), (3, '\u4e8c\u7ea7\u4e19\u7b49'), (4, '\u4e8c\u7ea7\u4e59\u7b49'), (5, '\u4e8c\u7ea7\u7532\u7b49'), (6, '\u4e09\u7ea7\u4e19\u7b49'), (7, '\u4e09\u7ea7\u4e59\u7b49'), (8, '\u4e09\u7ea7\u7532\u7b49'), (9, '\u4e09\u7ea7\u7279\u7b49')], max_length=20)),
                ('type', models.CharField(choices=[(0, '\u666e\u901a'), (1, '\u4e13\u79d1')], help_text='\u533b\u7597\u670d\u52a1\u662f\u5426\u4e13\u79d1', max_length=20, null=True)),
                ('information', models.TextField()),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('picture', models.CharField(help_text='\u533b\u9662\u7167\u7247\uff0c\u5b58\u8def\u5f84', max_length=90, null=True)),
                ('_createtime', models.CharField(max_length=20)),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Location')),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
    ]
