# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='_createtime',
            field=models.CharField(help_text='\u6ce8\u518c\u65f6\u95f4', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.CharField(help_text='\u7528\u6237\u540d\uff0c\u7528\u4e8e\u767b\u9646', max_length=15, unique=True),
        ),
    ]
