# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161124_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='id_location',
            field=models.ForeignKey(db_column='id_location', on_delete=django.db.models.deletion.CASCADE, to='users.Location'),
        ),
    ]
