# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161123_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='\u533b\u751f\u5b9e\u540d', max_length=45)),
                ('level', models.CharField(choices=[(0, '\u4e3b\u4efb\u533b\u5e08'), (1, '\u526f\u4e3b\u4efb\u533b\u5e08'), (2, '\u4e3b\u6cbb\u533b\u5e08'), (3, '\u4f4f\u9662\u533b\u5e08')], max_length=10)),
                ('information', models.TextField(blank=True)),
                ('picture', models.CharField(help_text='\u533b\u751f\u7167\u7247\uff0c\u5b58\u8def\u5f84', max_length=90, null=True)),
                ('speciality', models.CharField(help_text='\u4e3b\u6cbb\u7279\u957f', max_length=90, null=True)),
                ('careertime', models.IntegerField(default=0, help_text='\u533b\u9f84\uff0c\u5355\u4f4d\u4e3a\u5e74', max_length=3)),
                ('gender', models.CharField(choices=[(0, '\u7537'), (1, '\u5973')], max_length=10)),
                ('age', models.IntegerField(default=0, max_length=3)),
                ('_createtime', models.CharField(help_text='\u751f\u6210\u65f6\u95f4', max_length=100)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.AlterField(
            model_name='hospital',
            name='_createtime',
            field=models.CharField(max_length=100),
        ),
    ]
