# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161125_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpublisher',
            name='_createtime',
        ),
        migrations.RemoveField(
            model_name='adminreceptor',
            name='_createtime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='_createtime',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='_createtime',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='_createtime',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='_createtime',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='_createtime',
        ),
        migrations.AddField(
            model_name='adminpublisher',
            name='createtime',
            field=models.DateTimeField(blank=True, help_text='\u6ce8\u518c\u4e8b\u4ef6', null=True),
        ),
        migrations.AddField(
            model_name='adminreceptor',
            name='createtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='\u9884\u7ea6\u5355\u751f\u6210\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulletin',
            name='createtime',
            field=models.DateTimeField(blank=True, help_text='\u6700\u540e\u4e00\u6b21\u65b0\u589e\u9884\u7ea6\u8bb0\u5f55\u7684\u65f6\u95f4', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='createtime',
            field=models.DateTimeField(blank=True, help_text='\u751f\u6210\u65f6\u95f4', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='createtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='createtime',
            field=models.DateTimeField(blank=True, help_text='\u6ce8\u518c\u65f6\u95f4', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='registrationtime',
            field=models.DateTimeField(help_text='\u5230\u9662\u53d6\u53f7\u65f6\u95f4-\u6b64\u9879\u8bf4\u660e\u4e86\u662f\u5426\u723d\u7ea6'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='information',
            field=models.TextField(blank=True, default='\u65e0\u8bf4\u660e\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(blank=True, choices=[('\u666e\u901a', '\u666e\u901a'), ('\u4e13\u79d1', '\u4e13\u79d1')], default='\u666e\u901a', help_text='\u533b\u7597\u670d\u52a1\u662f\u5426\u4e13\u79d1', max_length=20, null=True),
        ),
    ]
