# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161124_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='careertime',
            field=models.IntegerField(default=0, help_text='\u533b\u9f84\uff0c\u5355\u4f4d\u4e3a\u5e74'),
        ),
    ]
