# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20161126_1058'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctordepartment',
            table='doctor_department',
        ),
    ]
