# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20161124_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('information', models.TextField(blank=True, help_text='\u6982\u8ff0', null=True)),
                ('id_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Hospital')),
            ],
            options={
                'db_table': 'departmenbt',
            },
        ),
    ]
