# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20161126_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id_adminreceptor',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='registrationtime',
            field=models.DateTimeField(blank=True, help_text='\u5230\u9662\u53d6\u53f7\u65f6\u95f4-\u6b64\u9879\u8bf4\u660e\u4e86\u662f\u5426\u723d\u7ea6', null=True),
        ),
    ]
