# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20161124_1046'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
