# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20161124_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDepartment',
            fields=[
                ('id_doctor_department', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Doctor')),
            ],
            options={
                'db_table': '_doctor_department',
            },
        ),
    ]
