# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_doctordepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminpublisher',
            fields=[
                ('id_adminpublisher', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('loginname', models.CharField(help_text='\u767b\u9646\u6807\u8bc6\u7b26\uff0c\u5b9e\u9645\u53ef\u4e3a\u81ea\u5b9a\u4e49\u7528\u6237\u540d\u6216\u9662\u65b9\u5b9a\u4e49\u7684\u7528\u6237\u540d(\u6bd4\u5982\u5de5\u53f7)', max_length=45)),
                ('password', models.CharField(max_length=32)),
                ('_createtime', models.CharField(max_length=100)),
                ('id_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Hospital')),
            ],
            options={
                'db_table': 'adminreceptor',
            },
        ),
    ]
