# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_adminpublisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpublisher',
            name='email',
            field=models.EmailField(help_text='\u9009\u586b\uff0c\u7528\u4e8e\u5907\u6848', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminpublisher',
            name='telephone',
            field=models.CharField(help_text='\u6216\u8bb8\u7528\u4e8e\u5907\u6848\u5b58\u6863\u7684\u4fe1\u606f', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='adminpublisher',
            name='_createtime',
            field=models.CharField(help_text='\u6ce8\u518c\u4e8b\u4ef6', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminpublisher',
            name='loginname',
            field=models.CharField(help_text='\u767b\u9646\u6807\u8bc6\u7b26\uff0c\u5b9e\u9645\u53ef\u4e3a\u81ea\u5b9a\u4e49\u7528\u6237\u540d\u6216\u88ab\u6ce8\u518c\u53d7\u7406\u65b9\u7ed9\u5b9a\u7684\u7528\u6237\u540d', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(help_text='\u9009\u586b\uff0c\u7528\u4e8e\u5907\u6848', max_length=50),
        ),
        migrations.AlterModelTable(
            name='adminpublisher',
            table=None,
        ),
    ]
