# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20161124_1124'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminpublisher',
            table='adminpublisher',
        ),
    ]
