# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20161124_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id_bulletin', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('availabletime', models.DateTimeField(help_text='\u53ef\u9884\u7ea6\u65f6\u95f4\u6bb5')),
                ('fee', models.FloatField(default=0, help_text='(\u9884\u7ea6)\u6302\u53f7\u8d39')),
                ('countavailable', models.IntegerField(help_text='\u521d\u59cb\u58f0\u660e\u7684\u53ef\u9884\u7ea6\u6570\u91cf', max_length=2)),
                ('countoccupied', models.IntegerField(help_text='\u5df2\u9884\u7ea6\u6570\u91cf', max_length=2)),
                ('_createtime', models.CharField(help_text='\u6700\u540e\u4e00\u6b21\u65b0\u589e\u9884\u7ea6\u8bb0\u5f55\u7684\u65f6\u95f4', max_length=100)),
                ('id_adminpublisher', models.ForeignKey(help_text='\u53d1\u5e03\u8005', on_delete=django.db.models.deletion.CASCADE, to='users.Adminpublisher')),
                ('id_doctor_department', models.ForeignKey(help_text='\u53ef\u9884\u7ea6\u7684\u533b\u751f', on_delete=django.db.models.deletion.CASCADE, to='users.DoctorDepartment')),
            ],
            options={
                'db_table': 'bulletin',
            },
        ),
    ]
