# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_bulletin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='countavailable',
            field=models.IntegerField(help_text='\u521d\u59cb\u58f0\u660e\u7684\u53ef\u9884\u7ea6\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='countoccupied',
            field=models.IntegerField(help_text='\u5df2\u9884\u7ea6\u6570\u91cf'),
        ),
    ]
