# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20161124_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminreceptor',
            fields=[
                ('id_adminreceptor', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('loginname', models.CharField(help_text='\u767b\u9646\u6807\u8bc6\u7b26\uff0c\u5b9e\u9645\u53ef\u4e3a\u81ea\u5b9a\u4e49\u7528\u6237\u540d\u6216\u9662\u65b9\u5b9a\u4e49\u7684\u7528\u6237\u540d(\u6bd4\u5982\u5de5\u53f7)', max_length=45, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('_createtime', models.CharField(max_length=100)),
                ('id_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Hospital')),
            ],
            options={
                'db_table': 'adminreceptor',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id_appointment', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('ispaid', models.BooleanField()),
                ('registrationtime', models.CharField(help_text='\u5230\u9662\u53d6\u53f7\u65f6\u95f4-\u6b64\u9879\u8bf4\u660e\u4e86\u662f\u5426\u723d\u7ea6', max_length=100)),
                ('_createtime', models.CharField(help_text='\u9884\u7ea6\u5355\u751f\u6210\u65f6\u95f4', max_length=100)),
                ('id_adminreceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Adminreceptor')),
                ('id_bulletin', models.ForeignKey(help_text='\u5206\u8bca\u53f0\u64cd\u4f5c\u5458\u4ece\u8fd9\u91cc\u53d6\u5f97\u9884\u7ea6\u4fe1\u606f', on_delete=django.db.models.deletion.CASCADE, to='users.Bulletin')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
