# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_adminreceptor_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ispaid',
            field=models.BooleanField(default=False),
        ),
    ]
